version: 0.0
os: linux
files:
  - source: /myjavaproject.war
    destination: /root/apache-tomcat-9.0.97/webapps/
hooks:    
  
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
