version: 0.0
os: linux
files:
  - source: /myjavaproject.war
    destination: /root/apache-tomcat-9.0.97/webapps/
hooks:    
  
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: start_shutdown.sh
      timeout: 300
      runas: root
 
