version: 0.0
os: linux
files: 
  - source: /*.war
    destination: /root/apache-tomcat-9.0.97/webapps/
hooks:    
  AfterInstall: 
     - location: scripts/server_start.sh
       timeout: 300
       runas: root
  ApplicationStop:
     - location: scripts/server_shutdown.sh
       timeout: 300
       runas: root

